#!/usr/bin/env bash
# Build the baseline-policy brain wasm:
#   build/nmmo3_brain.wasm  (sim/brain_shim.c + vendored puffernet.h
#                           + embedded vendor/upstream/resources/nmmo3/nmmo3_weights.bin)
#
# The weights are embedded as a generated C array (xxd -i at build time,
# written under build/, never committed) so the wasm needs no filesystem.
# Same STANDALONE_WASM reactor flags as sim/build_sim.sh. Memory sizing
# (verified against the MMONet construction, see sim/brain_shim.c header):
# ~17.7 MB embedded weights in .data + one 17.7 MB heap Weights copy +
# ~188 KB activations per batch-1 net (8 nets ~= 1.5 MB) ~= 37 MB total,
# so INITIAL_MEMORY=64mb avoids growth churn; ALLOW_GROWTH + the 1 GB
# ceiling + ABORTING_MALLOC are flag parity with the sim build.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

if ! command -v emcc >/dev/null 2>&1; then
    echo "error: emcc not found on PATH - install emscripten (brew install emscripten)" >&2
    exit 1
fi

mkdir -p build

WEIGHTS=vendor/upstream/resources/nmmo3/nmmo3_weights.bin
EMBED=build/nmmo3_weights_embedded.c
{
    printf '// generated by sim/build_brain.sh from %s - do not edit\n' "$WEIGHTS"
    printf 'const unsigned char nmmo3_weights_bin[] = {\n'
    xxd -i < "$WEIGHTS"
    printf '};\nconst unsigned int nmmo3_weights_bin_len = sizeof(nmmo3_weights_bin);\n'
} > "$EMBED"

COMMON_FLAGS=(-O2 -sSTANDALONE_WASM --no-entry -sINITIAL_MEMORY=64mb
              -sALLOW_MEMORY_GROWTH=1 -sMAXIMUM_MEMORY=1gb -sABORTING_MALLOC=1)

emcc "${COMMON_FLAGS[@]}" -I vendor/upstream sim/brain_shim.c "$EMBED" \
    -o build/nmmo3_brain.wasm

ls -la build/nmmo3_brain.wasm
echo "build_brain: OK"
